apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb/
  - redis/
  - panel/
  - kuber/
  - servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: pterodactyl
