apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - local-path-provisioner.yaml
  # - truenas-storage.yaml  # TODO: Fix YAML anchors (kustomize doesn't support anchors across documents)
  # - synology-storage.yaml  # TODO: Fix YAML anchors (kustomize doesn't support anchors across documents)
  # - nfs-storageclass.yaml  # Old Synology config (deprecated)
