apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - local-path-provisioner.yaml
  - truenas-storage.yaml
  - synology-storage.yaml
  # - nfs-storageclass.yaml  # Old Synology config (deprecated)
