apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

# Delete Flux network policies - they break connectivity with Cilium CNI
# because Cilium doesn't recognize the Kubernetes API as an "endpoint"
patches:
  - patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress
        namespace: flux-system
  - patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-scraping
        namespace: flux-system
  - patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-webhooks
        namespace: flux-system
