---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pterodactyl-panel
  labels:
    app: pterodactyl-panel
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pterodactyl.talos00`)
      kind: Rule
      services:
        - name: pterodactyl-panel
          port: 80
