---
apiVersion: v1
kind: Service
metadata:
  name: pterodactyl-panel
  labels:
    app: pterodactyl-panel
spec:
  type: ClusterIP
  selector:
    app: pterodactyl-panel
  ports:
    - name: http
      port: 80
      targetPort: 80
