apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/component: game-server
      app.kubernetes.io/part-of: gaming-stack
