---
# NodePort service for external game connectivity
apiVersion: v1
kind: Service
metadata:
  name: conan-exiles
  labels:
    app: conan-exiles
spec:
  type: NodePort
  selector:
    app: conan-exiles
  ports:
    - name: game
      port: 7777
      targetPort: 7777
      protocol: UDP
      nodePort: 30777
    - name: raw
      port: 7778
      targetPort: 7778
      protocol: UDP
      nodePort: 30778
    - name: query
      port: 27015
      targetPort: 27015
      protocol: UDP
      nodePort: 30015
