apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - postgresql/
  - prowlarr/
  - sonarr/
  - radarr/
  - overseerr/
  - plex/
  - jellyfin/
  - tdarr/
  - homepage/
  - common-env.yaml

commonLabels:
  app.kubernetes.io/part-of: arr-stack
