apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operator
  # Uncomment when 1Password credentials are ready
  # - onepassword-connect
  # - secretstores
