---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: libation
  labels:
    app: libation
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`libation.${CLUSTER_DOMAIN}`)
      kind: Rule
      services:
        - name: libation
          port: 3000
