apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-dev

resources:
  - ../../base/postgresql
  - ../../base/prowlarr
  - ../../base/sonarr
  - ../../base/radarr
  # - ../../base/readarr  # DISABLED: No compatible Docker images available for ARM64/x86-64
  - ../../base/overseerr
  - ../../base/plex
  - ../../base/jellyfin
  - ../../base/homepage
  - ../../base/exportarr
  - storage.yaml
