# Nebula Mesh VPN - Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
  # TODO: Add nebula resources when ready
  # - namespace.yaml  # Created at parent level
  # - configmap.yaml
  # - daemonset.yaml
  # - external-secret.yaml
