apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vpn-gateway

resources:
  - rbac.yaml
  - configmap-config.yaml
  - configmap-script.yaml
  - configmap-exporter.yaml
  - cronjob.yaml
  - exporter.yaml
  - grafana-dashboard.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: vpn-gateway
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
