apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - configmap.yaml
  - job.yaml

labels:
  - pairs:
      app.kubernetes.io/component: migration
      app.kubernetes.io/part-of: arr-stack
