---
apiVersion: v1
kind: Service
metadata:
  name: pterodactyl-mariadb
  labels:
    app: pterodactyl-mariadb
spec:
  type: ClusterIP
  selector:
    app: pterodactyl-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
