---
# Local access (HTTP)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw
  labels:
    app: openclaw
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`openclaw.talos00`)
      services:
        - name: openclaw
          namespace: home-automation
          port: 18789
