---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: posterr
  labels:
    app: posterr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`posterr.${CLUSTER_DOMAIN}`)
      kind: Rule
      services:
        - name: posterr
          port: 3000
