apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goldilocks
  namespace: infra-testing
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`goldilocks.talos00`)
      kind: Rule
      services:
        - name: goldilocks-dashboard
          port: 80
