# Liqo Multi-Cluster Federation - Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
# TODO: Add liqo resources when ready
# - helmrelease.yaml
# Peering is done via liqoctl, not static manifests
# - peering-secret.yaml
# - resource-offer.yaml
