---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tdarr
  labels:
    app: tdarr-server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tdarr.talos00`)
      kind: Rule
      services:
        - name: tdarr-server
          port: 8265
