apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tdarr

resources:
  - namespace.yaml
  - pvcs.yaml
  - server.yaml
  - worker-daemonset.yaml
  - services.yaml
  - ingressroute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: tdarr
