---
apiVersion: v1
kind: Service
metadata:
  name: tdarr-server
  labels:
    app: tdarr-server
spec:
  type: ClusterIP
  selector:
    app: tdarr-server
  ports:
    - name: http
      port: 8265
      targetPort: 8265
    - name: server
      port: 8266
      targetPort: 8266
---
# NodePort for external workers (Windows, non-K8s nodes)
apiVersion: v1
kind: Service
metadata:
  name: tdarr-external
  labels:
    app: tdarr-server
spec:
  type: NodePort
  selector:
    app: tdarr-server
  ports:
    - name: server
      port: 8266
      targetPort: 8266
      nodePort: 30266
