apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gluetun-socks
  namespace: vpn-gateway
  labels:
    app.kubernetes.io/name: gluetun
spec:
  entryPoints:
    - socks
  routes:
    - match: HostSNI(`*`)
      services:
        - name: gluetun
          port: 1080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gluetun-http-proxy
  namespace: vpn-gateway
  labels:
    app.kubernetes.io/name: gluetun
spec:
  entryPoints:
    - httpproxy
  routes:
    - match: HostSNI(`*`)
      services:
        - name: gluetun
          port: 8080
