apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vpn-gateway

resources:
  - namespace.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute-tcp.yaml

commonLabels:
  app.kubernetes.io/part-of: vpn-gateway
