apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: vpn-gateway
  labels:
    app.kubernetes.io/name: gluetun
spec:
  selector:
    app.kubernetes.io/name: gluetun
  ports:
    - name: socks
      port: 1080
      targetPort: 8888
      protocol: TCP
    - name: http-proxy
      port: 8080
      targetPort: 8888
      protocol: TCP
    - name: health
      port: 9999
      targetPort: 9999
      protocol: TCP
