apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - media-dev.yaml
  - media-dev-storage.yaml
  - media-prod.yaml
  - media-prod-storage.yaml
  - monitoring.yaml
  - observability.yaml
