apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets.yaml
  - home-automation.yaml
  - media.yaml
  - monitoring.yaml
  - observability.yaml
  - scratch.yaml
