---
# Frigate Web UI - Local access
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`frigate.talos00`)
      services:
        - name: frigate
          port: 5000
