---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: maintainerr
  labels:
    app: maintainerr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`maintainerr.${CLUSTER_DOMAIN}`)
      kind: Rule
      services:
        - name: maintainerr
          port: 6246
