---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  labels:
    app: maintainerr
    app.kubernetes.io/name: maintainerr
    app.kubernetes.io/part-of: arr-stack
spec:
  type: ClusterIP
  ports:
    - port: 6246
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: maintainerr
