---
# Traefik IngressRoute for DbGate
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dbgate
  namespace: scratch
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dbgate.talos00`)
      kind: Rule
      services:
        - name: dbgate
          port: 3000
