---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pulsarr
  labels:
    app: pulsarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pulsarr.${CLUSTER_DOMAIN}`)
      kind: Rule
      services:
        - name: pulsarr
          port: 3003
