---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-etcd
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-etcd
    release: kube-prometheus-stack
subsets:
  - addresses:
      - ip: 192.168.1.54
    ports:
      - name: http-metrics
        port: 2381
        protocol: TCP
