apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeview
  namespace: infra-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeview
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeview
subjects:
  - kind: ServiceAccount
    name: kubeview
    namespace: infra-control
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeview
  namespace: infra-control
  labels:
    app: kubeview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeview
  template:
    metadata:
      labels:
        app: kubeview
    spec:
      serviceAccountName: kubeview
      containers:
        - name: kubeview
          image: ghcr.io/benc-uk/kubeview:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: IN_CLUSTER
              value: 'true'
          resources:
            requests:
              memory: '128Mi'
              cpu: '10m'
            limits:
              memory: '256Mi'
              cpu: '100m'
---
apiVersion: v1
kind: Service
metadata:
  name: kubeview
  namespace: infra-control
  labels:
    app: kubeview
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: kubeview
