apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaming

resources:
  - windows-vm.yaml
  - windows-service.yaml
  - virtio-drivers-dv.yaml
  - windows-setup-scripts.yaml
  - novnc.yaml
  - guacamole.yaml
