apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaming

resources:
  - namespace.yaml
  - common-env.yaml
  - opensim/
  - pterodactyl/

labels:
  - pairs:
      app.kubernetes.io/part-of: gaming-stack

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 3
