apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: infra-control
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`headlamp.talos00`)
      kind: Rule
      services:
        - name: headlamp
          port: 80
