apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium-dns
  namespace: dns
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dns.talos00`)
      kind: Rule
      services:
        - name: technitium-dns
          port: 5380
