apiVersion: v1
kind: Service
metadata:
  name: technitium-dns
  namespace: dns
  labels:
    app: technitium-dns
spec:
  type: ClusterIP
  selector:
    app: technitium-dns
  ports:
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: http
    port: 5380
    targetPort: 5380
    protocol: TCP
