---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - users-database.yaml
  - configmap.yaml
  - deployment.yaml
  - ingressroute.yaml
  - middleware.yaml
