apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scratch

resources:
  - ghcr-secret.yaml
  - deployment-go.yaml
  - deployment-python.yaml
  - service-go.yaml
  - service-python.yaml
  - servicemonitor.yaml
  - mtls-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: grpc-example
