apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grpc-go-mtls
spec:
  endpointSelector:
    matchLabels:
      app: grpc-go
  ingress:
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "50051"
              protocol: TCP
            - port: "9090"
              protocol: TCP
      authentication:
        mode: "required"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grpc-python-mtls
spec:
  endpointSelector:
    matchLabels:
      app: grpc-python
  ingress:
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "50052"
              protocol: TCP
            - port: "9091"
              protocol: TCP
      authentication:
        mode: "required"
