---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpc-go
  labels:
    app: grpc-go
    app.kubernetes.io/name: grpc-go
    app.kubernetes.io/part-of: grpc-example
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: grpc-go
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpc-python
  labels:
    app: grpc-python
    app.kubernetes.io/name: grpc-python
    app.kubernetes.io/part-of: grpc-example
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: grpc-python
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
