---
apiVersion: v1
kind: Service
metadata:
  name: grpc-python
  labels:
    app: grpc-python
    app.kubernetes.io/name: grpc-python
    app.kubernetes.io/part-of: grpc-example
spec:
  type: ClusterIP
  selector:
    app: grpc-python
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
