apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubeview
  namespace: infra-testing
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kubeview.talos00`)
      kind: Rule
      services:
        - name: kubeview
          port: 80
