---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebula-system

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - daemonset.yaml

commonLabels:
  app.kubernetes.io/part-of: hybrid-llm-cluster
  app.kubernetes.io/managed-by: kustomize
