---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scratch

resources:
  # namespace.yaml removed - managed by infrastructure/base/namespaces/
  - example-postgres/
  - example-mongodb/
  - dbgate/
  - frigate/
