---
# Local access (HTTP)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omnitools
  labels:
    app: omnitools
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`omnitools.talos00`)
      services:
        - name: omnitools
          namespace: home-automation
          port: 80
