---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pterodactyl-kuber-config
  labels:
    app: pterodactyl-kuber
data:
  config.yml: |
    debug: false
    uuid: f94cc59e-5050-4b50-8801-086d68ff38ad
    token_id: nfkHBfODya1fr3Hl
    token: lmBY8Woj1HtUmryxTXOP3TmWgE1OtITc0lVeE9lKyvnxqEifBlksKGoOSMuhKHnr
    api:
      host: 0.0.0.0
      port: 8080
      ssl:
        enabled: false
      upload_limit: 100
    system:
      data: /var/lib/kubectyl/volumes
      sftp:
        bind_port: 2022
        sftp_image: 'ghcr.io/kubectyl/sftp-server:latest'
    cluster:
      host: kuber.talos00
      bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkxRMkJHcWFzdWpKelI3RmhhM05VZ0FIMWRzbFRidWhoRWM4bUZLaDBteFkifQ.eyJhdWQiOlsiaHR0cHM6Ly8xOTIuMTY4LjEuNTQ6NjQ0MyJdLCJleHAiOjIwODQ5MDc3MDAsImlhdCI6MTc2OTU0NzcwMCwiaXNzIjoiaHR0cHM6Ly8xOTIuMTY4LjEuNTQ6NjQ0MyIsImp0aSI6ImJlODkxMTk0LWViZGUtNDg3MC05ODE5LThjNTY2Mzk4MDk5YyIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoiZ2FtaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InB0ZXJvZGFjdHlsLWt1YmVyIiwidWlkIjoiMmUwYjFmNWMtZTcwYy00MGQyLWEzYTQtZmEyZmY1ZWE0Mzk2In19LCJuYmYiOjE3Njk1NDc3MDAsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpnYW1pbmc6cHRlcm9kYWN0eWwta3ViZXIifQ.oID9IhuM-aRfknqb9uldT2hLVsBmXZbhAXe7rVbIBVusdlv5MIJrtQZcWUx7JccERYyzfzvxmsD1PGiRqKUcKleBOzr2DvXRUS-BudR5LT6NqFx9tPhiZtD1Bbx-y3mZ8Ce6euOAHByqGfTJezS58OJ002Uxxj8RsYyd8i4k_IZhhZTZNqHburpy8XwxGHyL1SczMwjjszHG2qDuxUqOsbIwSF4kTfHV8xfT5Oq2Ezl3hx4gNlFpGv5e9zbzaPB1sTtQBnWFyRbBT03d5Tb4_9ca0pLrwyRRyiNWleDhZhydVfHrLZfaig_Dds9iNJwyLOqdHf_LoxUtwEmfLIAQsAd-v6yoshX_iRaCJouIVB3z8-EoOpXCXbCk9WeLvec4D4wqkXMOVI7SgltElynria_O9Qgsrwj5sXOgPZkLPgkDE_9UF1XBwJ0FomdaEXyeZpc5kBISOJQmPh--PZu2jdgzkeXqw8y0RmeDdX8Z6-TXwdN6xvO4qJtHchMeAFaondFOWArwc1cC0hsqf3rnppwKi1p5jZAi5ZDetMlaLymJnrOuo8f_r_gkJ8Fx_9yjXmWN1k-5u_1KXEMSs7cAVLjHvG9h4gz2dbi5MWhqpU2DMJUOAhmGROTy1e8xJI5HJkzvYhueEKpxGpLSme6dKjSAhsRtmleFmjjVsPAHuJk
      namespace: gaming
      insecure: true
      metrics: metrics_api
      dns_policy: clusterfirst
      image_pull_policy: ifnotpresent
      storage_class: local-path
      snapshot_class: none
      service_type: loadbalancer
      external_traffic_policy: cluster
      metallb_shared_ip: true
    allowed_mounts: []
    remote: 'http://pterodactyl.talos00'
