---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pterodactyl-kuber
  labels:
    app: pterodactyl-kuber
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kuber.talos00`)
      kind: Rule
      services:
        - name: pterodactyl-kuber
          namespace: gaming
          port: 8080
