---
apiVersion: v1
kind: Service
metadata:
  name: pterodactyl-kuber
  labels:
    app: pterodactyl-kuber
spec:
  type: ClusterIP
  selector:
    app: pterodactyl-kuber
  ports:
    - name: http
      port: 8080
      targetPort: 8080
