apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poisonarr

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: poisonarr
    includeSelectors: false
