apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-migration-configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/component: shared
      app.kubernetes.io/part-of: arr-stack
