apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ops-view
  namespace: infra-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ops-view
rules:
  - apiGroups: ['']
    resources:
      - nodes
      - pods
    verbs: ['get', 'list']
  - apiGroups: ['metrics.k8s.io']
    resources:
      - nodes
      - pods
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ops-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ops-view
subjects:
  - kind: ServiceAccount
    name: kube-ops-view
    namespace: infra-control
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ops-view
  namespace: infra-control
  labels:
    app: kube-ops-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ops-view
  template:
    metadata:
      labels:
        app: kube-ops-view
    spec:
      serviceAccountName: kube-ops-view
      containers:
        - name: kube-ops-view
          image: hjacobs/kube-ops-view:latest
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: '100Mi'
              cpu: '100m'
---
apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
  namespace: infra-control
  labels:
    app: kube-ops-view
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: kube-ops-view
