apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kube-ops-view
  namespace: infra-control
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kube-ops-view.talos00`)
      kind: Rule
      services:
        - name: kube-ops-view
          port: 80
