---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liqo

resources:
  - namespace.yaml
  - helmrelease.yaml
  # Peering is applied after Liqo is installed and AWS cluster is provisioned
  # - aws-gpu-cluster-peering.yaml

commonLabels:
  app.kubernetes.io/part-of: hybrid-llm-cluster
  app.kubernetes.io/managed-by: kustomize
