---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liqo

resources:
  - namespace.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/part-of: hybrid-llm-cluster
  app.kubernetes.io/managed-by: kustomize
