---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - rbac.yaml
  - cronjob.yaml

configMapGenerator:
  - name: pod-cleanup-script
    files:
      - cleanup.py
    options:
      disableNameSuffixHash: true

# Note: GrafanaDashboard for this job is in monitoring/grafana-dashboards/pod-cleanup.yaml
# TODO: probably should move it here???
