---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: scrypted
  labels:
    app: scrypted
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`scrypted.talos00`)
      kind: Rule
      services:
        - name: scrypted
          port: 11080
