---
apiVersion: v1
kind: Service
metadata:
  name: scrypted
  labels:
    app: scrypted
spec:
  selector:
    app: scrypted
  ports:
    - name: http
      port: 11080
      targetPort: 11080
      protocol: TCP
    - name: https
      port: 10443
      targetPort: 10443
      protocol: TCP
    - name: rtsp
      port: 8554
      targetPort: 8554
      protocol: TCP
    - name: rtsp-tcp
      port: 8555
      targetPort: 8555
      protocol: TCP
