---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: posterizarr
  labels:
    app: posterizarr
    app.kubernetes.io/name: posterizarr
    app.kubernetes.io/part-of: arr-stack
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`posterizarr.talos00`)
      kind: Rule
      services:
        - name: posterizarr
          port: 8000
