apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingressroute.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - tdarr-node-daemonset.yaml

labels:
  - pairs:
      app.kubernetes.io/component: transcoder
      app.kubernetes.io/part-of: arr-stack
