---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  labels:
    app: tdarr
    app.kubernetes.io/name: tdarr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8265
      targetPort: http
      protocol: TCP
    - name: server
      port: 8266
      targetPort: server
      protocol: TCP
  selector:
    app: tdarr
