---
apiVersion: v1
kind: Service
metadata:
  name: readarr
  labels:
    app: readarr
    app.kubernetes.io/name: readarr
    app.kubernetes.io/part-of: arr-stack
spec:
  type: ClusterIP
  ports:
    - port: 8787
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: readarr
