apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingressroute.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - backup-cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/component: media-server
      app.kubernetes.io/part-of: arr-stack
