---
# Graylog IngressRoute
# NOTE: Graylog is currently scaled to 0 replicas
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: graylog
  namespace: observability
  labels:
    app: graylog
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`graylog.talos00`)
      kind: Rule
      services:
        - name: graylog
          port: 9000
