# Linkerd Service Mesh
# Deployed via Helm - see scripts/deploy-linkerd.sh
#
# This kustomization is for tracking/documentation purposes.
# The actual deployment uses Helm charts:
#   - linkerd-edge/linkerd-crds
#   - linkerd-edge/linkerd-control-plane
#
# Values files:
#   - values-crds.yaml
#   - values-control-plane.yaml
#
# To deploy:
#   ./scripts/deploy-linkerd.sh install
#
# To inject a namespace:
#   ./scripts/deploy-linkerd.sh inject scratch
#
# To uninstall:
#   ./scripts/deploy-linkerd.sh uninstall

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# No resources - managed by Helm
# This file exists for documentation and future GitOps integration
