---
apiVersion: v1
kind: Service
metadata:
  name: exportarr-prowlarr
  labels:
    app: exportarr-prowlarr
spec:
  ports:
    - port: 9707
      targetPort: metrics
      name: metrics
  selector:
    app: exportarr-prowlarr
---
apiVersion: v1
kind: Service
metadata:
  name: exportarr-sonarr
  labels:
    app: exportarr-sonarr
spec:
  ports:
    - port: 9707
      targetPort: metrics
      name: metrics
  selector:
    app: exportarr-sonarr
---
apiVersion: v1
kind: Service
metadata:
  name: exportarr-radarr
  labels:
    app: exportarr-radarr
spec:
  ports:
    - port: 9707
      targetPort: metrics
      name: metrics
  selector:
    app: exportarr-radarr
---
apiVersion: v1
kind: Service
metadata:
  name: exportarr-readarr
  labels:
    app: exportarr-readarr
spec:
  ports:
    - port: 9707
      targetPort: metrics
      name: metrics
  selector:
    app: exportarr-readarr
