apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - configmap-services.yaml
  - externalsecret.yaml

labels:
  - pairs:
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/part-of: arr-stack
