---
# Tempo Operator - Installed via raw manifests from GitHub releases
# Provides CRDs: TempoStack, TempoMonolithic
#
# The tempo-operator doesn't have a Helm chart.
# We use kustomize's remote URL support to install from GitHub releases.
#
# Reference: https://github.com/grafana/tempo-operator/releases
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/grafana/tempo-operator/releases/download/v0.19.0/tempo-operator.yaml
